canonicalBaseUrl: "https://example.org/mapnificent"
baseurl: "/mapnificent"
tileUrl: "//cartodb-basemaps-{s}.global.ssl.fastly.net/rastertiles/voyager/{z}/{x}/{y}@2x.png"
indexTileUrl: "//cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png"
defaults:
  -
    scope:
      path: ""
      type: "cities"
    values:
      layout: "city"
      permalink: "/:slug/"

collections:
  cities:
    output: true
    permalink: /:path/


plugins:
  - jekyll-redirect-from

# Ignore our `vendor` folder from Bundler
# https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902
exclude: [vendor, _cities/**/scripts, __cities, _cities/**/data, node_modules, src, dist]
